project 'AugmentedRealityTest.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AugmentedRealityTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AugmentedRealityTest
  pod 'FileBrowser', '~> 1.0'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'  
  target 'AugmentedRealityTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AugmentedRealityTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
